title: Jozen Site
description: A site to learn Unity and etc...
theme: minima
baseurl: ""  # サブディレクトリにデプロイする場合はここにパスを指定
url: "https://yjozen.github.io"  # GitHub Pages の URL

collections:
  pages:
    output: true

# GitHub Pages のプラグインを有効にします
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives


# Markdown 設定
markdown: kramdown
highlighter: rouge


