title: Jozen Site
description: A site to learn Unity and etc...
theme: minima
baseurl: "/Unity_Lesson//docs"  # サブディレクトリにデプロイする場合はここにパスを指定
url: "https://yjozen.github.io"  # GitHub Pages の URL

# Markdown 設定
markdown: kramdown
highlighter: rouge

collections:
  pages:
    output: true

permalink: /:path/

# GitHub Pages のプラグインを有効にします
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives





